print ("Presentation: Exploring Huron-Wendat Heritage")
print()
print("Key aspects of Huron-Wendat culture:")
print("Traditional Practices, Art and Craftsmanship, Language and Storytelling, and Community Traditions.")
print()
print ("Date: September 8 2023")
print("Duration: 60 minutes")
